# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
def open_asset(file_name)
  File.open(Rails.root.join('db', 'seed_assets', file_name))
end
Park.destroy_all
parks_canadian = [
    {
      full_name: "Banff National Park",
      name: "Banff",
      country: "Canada",
      prov_state: "Alberta",
      lat: 51.1667,
      long: -115.55,
      description: "Canada's oldest national park and was established in 1885.  Located in the Rocky Mountains, 110–180 kilometres  ,68–112 mi} west of Calgary in the province of Alberta, Banff encompasses 6,641 square kilometres  ,2,564 sq mi}[2] of mountainous terrain, with numerous glaciers and ice fields, dense coniferous forest, and alpine landscapes",
      url: "https://www.pc.gc.ca/en/pn-np/ab/banff", 
      established: 1885,
      unesco: true,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/banff.jpg"
    },
    {
      full_name: "Waterton Lakes National Park",
      name:"Waterton Lakes",
      country: "Canada",
      prov_state:"Alberta",
      lat: 49.0833,
      long: -113.8667,
      description: "The prairies of Alberta meet the peaks of the Rocky Mountains in Waterton Lakes National Park. This beautiful landscape was impacted by a wildfire in September 2017, resulting in areas of the park being closed to the public.",
      url: "https://www.pc.gc.ca/en/pn-np/ab/waterton",
      established: 1885,
      unesco: true,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/waterton.jpg"
    },
    {
      full_name: "Jasper National Park",
      name: "Jasper",
      country: "Canada",
      prov_state: "Alberta",
      lat:52.8731,
      long: -118.0823,
      description:"Extending over 11,000 square kilometres, it's the largest national park in the Canadian Rockies. Find your connection to this special place by discovering one or all of our five spectacular regions by exploring our extensive trail network.",
      url:"https://www.pc.gc.ca/en/pn-np/ab/jasper",
      established: 1907,
      unesco: true,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/jasper.jpg"
    },
    {
      full_name: "Yoho National Park",                    
      name: "Yoho",
      country: "Canada",
      prov_state: "British Columbia",
      lat: 51.3666,
      long: -116.5485,
      description: "Yoho covers 1,313 km2  ,507 mi2} and it is the smallest of the four contiguous national parks.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/yoho",
      established: 1886,
      unesco: true,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/yoho.jpg"
    },
    {
      full_name: "Elk Island National Park",
      name: "Elk Island",
      country: "Canada",
      prov_state: "Alberta",
      lat: 53.5928,
      long: -112.8708,
      description: "Just 35 minutes east of Edmonton lies a natural wonderland open all year long! Spread a blanket and gaze at a starry sky free from city lights or follow the footprints of a bison and learn how this magnificent animal was brought back from near extinction. In addition to being an important refuge for bison, elk and more than 250 bird species.",
      url: "https://www.pc.gc.ca/en/pn-np/ab/elkisland",
      established: 1913,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/elk-island.jpg"
    },
    {
      full_name: "Mount Revelstoke National Park",
      name: "Mount Revelstoke",
      country: "Canada",
      prov_state: "British Columbia",
      lat: 51.092604,
      long: -118.042224,
      description: "Take a cool stroll through a lush rainforest on a hot summer day. Stand at the point of no return, where champions once launched themselves down a world-famous ski jump, and imagine the thrill of flight. Climb the only mountain in the national park system that you can summit just a short walk from your car – all at Mount Revelstoke National Park.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/revelstoke",
      established: 1914,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/mount-revelstoke-national-park.jpg"
    },
    {
      full_name: "Thousand Islands National Park",
      name: "Thousand Islands",
      country: "Canada",
      prov_state: "Ontario",
      lat: 44.3339,
      long: -75.9948,
      description: "Journey to the picturesque granite islands and windswept pine trees of Thousand Islands National Park. Discover rare species of turtles and birdlife alongside undulating hiking trails.",
      url: "https://www.pc.gc.ca/en/pn-np/on/1000",
      established: 1904,
      unesco: false, 
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/thousand-islands.jpg"
    },
    {
      full_name: "Point Pelee National Park",
      name: "Point Pelee",
      country: "Canada",
      prov_state: "Ontario",
      lat: 41.9642,
      long: -82.5178,
      description: "At the southernmost point of the Canadian mainland - Point Pelee National Park, experience nature like never before. Whether you cycle, paddle or hike Canada’s smallest but most ecologically diverse national park, you’ll be immersed in an unforgettable eco-adventure.",
      url: "https://www.pc.gc.ca/en/pn-np/on/pelee",
      established: 1987,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/point-pelee.jpg"
    },
    {
      full_name: "Prince Edward Island National Park",
      name: "Prince Edward Island",
      country: "Canada",
      prov_state: "Prince Edward Island",
      lat: 46.415714,
      long: -63.073203,
      description: "Gentle surf strokes sandy beaches alongside red cliffs and wind-sculpted dunes. Cycle a seashore path, savour a picnic by a lighthouse and spot heron wading in coastal bays. Hike woodlands and overlook ponds watching for red fox, waterfowl and warblers, then head to one of many beaches to build spectacular sandcastles. ",
      url:"https://www.pc.gc.ca/en/pn-np/pe/pei-ipe",
      established: 1937,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/prince-edward-island.jpg"
    },
    {
      full_name: "Cape Breton Highlands National Park",
      name: "Cape Breton Highlands",
      country: "Canada",
      prov_state: "Nova Scotia",
      lat: 46.81351,
      long: -60.768602,
      description: "One of Canada’s most enchanting places, where the mountains meet the sea. As you hug the world-famous Cabot Trail coastline you'll wind through Cape Breton Highlands National Park, where lush, forested river canyons carve into the ancient plateau, edged by rust-coloured cliffs.",
      url: "https://www.pc.gc.ca/en/pn-np/ns/cbreton",
      established: 1936,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/cape-breton.jpg"
    },
    {
      full_name: "Georgian Bay Islands National Park",
      name: "Georgian Bay Islands",
      country: "Canada",
      prov_state: "Ontario",
      lat: 44.874317,
      long: -79.869955,
      description: "Welcome to the world’s largest freshwater archipelago—home to a boat-access nature preserve situated where the windswept white pines and granite shores of the Canadian Shield turn to dense deciduous woodland. Here, adventure is easy.",
      url: "https://www.pc.gc.ca/en/pn-np/on/georg",
      established: 1929,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/georgian-bay.jpg"
    },
    {
      full_name: "Wood Buffalo National Park",
      name: "Wood Buffalo",
      country: "Canada",
      prov_state: ["Alberta", "Northwest Territories"],
      lat: 59.3908,
      long: -112.9864,
      description: "Wood Buffalo National Park of Canada is our country's largest national park and one of the largest in the world. It was established in 1922 to protect the last remaining herds of bison in northern Canada. Today, it protects an outstanding and representative example of Canada's Northern Boreal Plains.",
      url: "https://www.pc.gc.ca/en/pn-np/nt/woodbuffalo",
      established: 1922,
      unesco: true,  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/wood-buffalo.jpg"
    },
    {
      full_name: "Prince Albert National Park",
      name: "Prince Albert",
      country: "Canada",
      prov_state: "Saskatchewan",
      lat: 53.9633,
      long: -106.37,
      description: "Whether your idea of adventure is portaging a canoe between remote forest lakes or a day of pulse-racing waterskiing and wakeboarding, Prince Albert National Park satisfies with a mix of wilderness and accessibility.",
      url: "https://www.pc.gc.ca/en/pn-np/sk/princealbert",
      established:1927,
      unesco: false,  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/prince-albert-np.jpg"
    },
    {
      full_name: "Riding Mountain National Park",
      name: "Riding Mountain",
      country: "Canada",
      prov_state: "Manitoba",
      lat: 50.8639,
      long: -100.0361,
      description: "Yellow goldenrods sway in prairie meadows and a gentle breeze blows through the aspen. Black bears pad along boreal trails and the piercing sound of elk bugling echoes around the forest. Visit Grey Owl’s historic cabin and see the enduring landmark of the East Gate",
      url: "https://www.pc.gc.ca/en/pn-np/mb/riding",
      established: 1933,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/riding-mountain.jpg"
    },
    {
      full_name: "Kootenay National Park",
      name: "Kootenay",
      country: "Canada",
      prov_state: "British Columbia",
      lat:  50.8831,
      long: -116.0492,
      description: "Established in 1920 as part of an agreement to build a new road across the Rockies, Kootenay National Park is a place of unique contrasts, from icy mountain rivers to steamy hot springs. Take a 60-minute scenic drive and discover a new surprise around every bend.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/kootenay",
      established:1920,
      unesco: true, 
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/kootenay.jpg"
    },
    {
      full_name: "Fundy National Park",
      name: "Fundy",
      country: "Canada",
      prov_state: "New Brunswick",
      lat: 45.613777,
      long: -65.031631,
      description: "Experience the world’s highest tides – not to mention pristine forests, deluxe campgrounds and a taste of Atlantic Canada culture – at Fundy National Park. Paddle in a kayak as the waters rise up to 12 metres or more.",
      url: "https://www.pc.gc.ca/en/pn-np/nb/fundy",
      established: 1948,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/fundy.jpg"
    },
    {
      full_name: "Terra Nova National park",
      name: "Terra Nova",
      country: "Canada",
      prov_state: "Newfoundland and Labrador",
      lat: 48.525265, 
      long: -53.965517,
      description: "Escape. Explore. Experience… The wonder and drama of Canada’s most Easterly National Park, Terra Nova. It’s a magical place where the land and sea compete for your attention, where the island boreal forest reveals its natural and cultural secrets as you hike a trail and where you can experience an evening of theatre under the stars.",
      url: "https://www.pc.gc.ca/en/pn-np/nl/terranova",
      established: 1957,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/terra-nova-national-park.jpg"
    },
    {
      full_name: "Kejimkukik National Park",
      name: "Kejimkukik",
      country: "Canada",
      prov_state: "Nova Scotia",
      lat: 44.438428,
      long: -65.208528,
      description: "Kejimujik National Park Seaside is a separate protected wilderness on the Atlantic coast where you can experience pristine white sand beaches, astounding turquoise waters, coastal bogs, abundant wildflowers, rich lagoon systems, and coastal wildlife.",
      url: "https://www.pc.gc.ca/en/pn-np/ns/kejimkujik",
      established: 1967,
      unesco: false, 
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/kejimkujik.jpg"
    },
    {
      full_name: "Kouchibouguac National Park",
      name: "Kouchibouguac",
      country: "Canada",
      prov_state: "New Brunsiwick",
      lat: 46.799695, 
      long: -64.964627,
      description: "Discover a national park on New Brunswick’s Acadian Coast where lush mixed-wood forests lead to colorful salt marshes and warm ocean beaches. Offshore, golden sand dunes foster calm seas. At night, this Dark Sky Preserve is a celestial masterpiece; in winter, it is a snowbound fun zone. And each of these natural wonders intertwines with fascinating Mi’gmaq and Acadian cultures. Welcome to Kouchibouguac National Park—an awe-inspiring all-season destination.",
      url: "https://www.pc.gc.ca/en/pn-np/nb/kouchibouguac",        
      established: 1969,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/Kouchibouguac.jpg"
    },
    {
      full_name: "Pacific Rim National Park Reserve",
      name: "Pacific Rim",
      country: "Canada",
      prov_state: "British Columbia",
      lat: 48.791931, 
      long: -125.156359,
      description: "Suit up in your storm gear and watch the winter breakers crash on a rocky shoreline, or enjoy a summer stroll along an endless sandy beach.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/pacificrim",
      established: 1970,
      unesco: false,    
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/pacific-rim.jpg"
    },
    {
      full_name: "Forillon National Park",
      name: "Forillon",
      country: "Canada",
      prov_state: "Quebec",
      lat: 48.838692, 
      long: -64.478524,
      description: "Forillon National Park offers a wide range of experiences by the sea, along cliffs and in the forest. Prefer a quiet stroll across a pebble beach? Want to look into history by opening the door to a beautiful yellow house overlooking the bay? Go snorkelling and discover colourful underwater plant and wildlife.",
      url: "https://www.pc.gc.ca/en/pn-np/qc/forillon/",
      established: 1970,
      unesco: false,          
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/forillon.jpg"
    },
    {
      full_name: "La Maurice National Park",
      name: "La Maurice", 
      country: "Canada",
      prov_state: "Quebec",
      lat: 46.720085, 
      long: -72.765907,
      description: "As well as forests of conifers and hardwoods, La Mauricie will treat you to touches of azure: the Park has more than 150 lakes of various sizes.",
      url: "https://www.pc.gc.ca/en/pn-np/qc/mauricie",
      established: 1970,
      unesco: false,   
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/la-maurice.jpg"
    },
    {
      full_name: "Sable Island National Park Reserve",
      name: "Sable Island",
      country: "Canada",
      prov_state: "Nova Scotia",
      lat: 43.932092, 
      long: -59.906766,
      description: "A wild and windswept island of sand sits far out in the North Atlantic, its iconic crescent shape emerging from the expanse of the sea. Isolated and remote, Sable Island is one of Canada’s furthest offshore islands. Shifting sand dunes, among Eastern Canada’s largest, dominate the landscape.",
      url: "https://www.pc.gc.ca/en/pn-np/ns/sable",                    
      established:2013,
      unesco: false,                  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/sable-island-national-park.jpg"
    },
    {
      full_name: "Gros Morne National Park",
      name: "Gros Morne", 
      country: "Canada",
      prov_state: "Newfoundland and Labrador",
      lat: 49.652015, 
      long: -57.755758000000014,
      description: "Soaring fjords and moody mountains tower above a diverse panorama of beaches and bogs, forests and barren cliffs. Shaped by colliding continents and grinding glaciers, Gros Morne’s ancient landscape is trully on of a kind.",
      url: "https://www.pc.gc.ca/en/pn-np/nl/grosmorne",                         
      established: 1987,
      unesco: true,                     
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/gros-morne.jpg"
    },
    {
      full_name: "Pukaskwa National Park",
      name:"Pukaskwa",
      country: "Canada",
      prov_state: "Ontario",
      lat: 48.245678, 
      long: -85.887781,
      description: "Waves roll across immense Lake Superior and crash against a remote granite shore. Tracts of windswept spruce and pine reach beyond the horizon from towering cliffs and along secluded sandy beaches.",
      url: "https://www.pc.gc.ca/en/pn-np/on/pukaskwa",
      established: 1978,
      unesco: false,       
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/pukaskwa.jpg"
    },
    {
      full_name: "Kluane National Park and Reserve",
      name: "Kluane",
      country: "Canada",
      prov_state: "Yukon",
      lat: 60.75, 
      long: -139.5,
      description: "Kluane – high in the mountains of southwest Yukon – is a land of extremes. The park is home to Canada’s highest peak  ,5,959-metre Mount Logan}, its largest ice field and North America’s most genetically diverse grizzly population.",
      url: "https://www.pc.gc.ca/en/pn-np/yt/kluane",
      established: 1972,
      unesco: false,   
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/kluane.jpg"
    },
    {
      full_name: "Nahanni National Park and Reserve",
      name:"Nahanni",
      country: "Canada",
      prov_state: "Northwest Territories",
      lat: 61.500697, 
      long: -125.500469,
      description: "The Cirque of the Unclimbables’ granite spires rise out of the lush alpine meadow, at Náįlįcho  ,Virginia Falls} the South Nahanni River surges over a drop twice the height of Niagara Falls. ",
      url: "https://www.pc.gc.ca/en/pn-np/nt/nahanni",
      established: 1972,
      unesco: true,   
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/nahanni.jpg"
    },
    {
      full_name: "Auyuittuq National Park",
      name: "Auyuittuq",
      country: "Canada",
      prov_state: "Nunavut",
      lat: 67.489532, 
      long: -66.055959,
      description: "A zig-zag skyline of craggy granite peaks and glittering glaciers overlooks tundra valleys and steep-walled fiords whose winding waterways teem with narwhal and ringed seals, Auyuittuq is a diverse and grand-scale Arctic experience.",
      url: "https://www.pc.gc.ca/en/pn-np/nu/auyuittuq",
      established: 1972,
      unesco: false,    
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/auyuittuq.jpg"
    },
    {
      full_name: "Grasslands National park",
      name: "Grasslands",
      country: "Canada",
      prov_state: "Saskatchewan",
      lat: 49.101935, 
      long: -107.264871,
      description: "Experience the solitude of the wide-open plain as the prairie wind ripples a sea of grasses beneath the clear blue sky. Ride a traditional wagon, sit before a crackling campfire or spend the night beneath a canopy of brilliant stars.",
      url:"https://www.pc.gc.ca/en/pn-np/sk/grasslands",
      established: 1981,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/grasslands.jpg"
    },
    {
      full_name: "Ivvavik National Park",
      name: "Ivvavik",
      country: "Canada",
      prov_state: "Yukon",
      lat: 69.094186, 
      long: -139.833984,
      description: "Ivvavik, meaning ‘a place for giving birth, a nursery,' in Inuvialuktun, the language of the Inuvialuit, is the first national park in Canada to be created as a result of an aboriginal land claim agreement. The park protects a portion of the calving grounds of the Porcupine caribou herd and represents the Northern Yukon and Mackenzie Delta natural regions.",
      url: "https://www.pc.gc.ca/en/pn-np/yt/ivvavik",
      established: 1984,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/ivvavik.jpg"
    },
    {
      full_name: "Mingan Archipelago National Park and Reserve",
      name: "Mingan",
      country: "Canada",
      prov_state: "Quebec",
      lat: 50.212818, 
      long: -63.889893,
      description: "Instantly captivating, the Mingan Archipelago features colossal limestone outcroppings that evoke landscapes from primeval times. Frolicking whales and seals enliven the vast, blue horizon, while over 1,000 islands and islets enchant visitors with their unique flora and seabird colonies.",
      url: "https://www.pc.gc.ca/en/pn-np/qc/mingan",
      established: 1984,
      unesco: false,  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/mingan.jpg"
    },
    {
      full_name: "Quttinirpaaq National Park",
      name: "Quttinirpaaq",
      country: "Canada",
      prov_state: "Nunavut",
      lat: 81.467247, 
      long: -72.109083,
      description: "Shimmering ice caps are punctured by jagged black peaks and massive glaciers fuel wild rivers. White Arctic hare graze amid a purple saxifrage-dotted landscape while ancient peoples’ camps and explorers’ shelters dot rugged, pristine Quttinirpaaq.",
      url: "https://www.pc.gc.ca/en/pn-np/nu/quttinirpaaq",
      established: 1988,
      unesco: false,   
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/quttinirpaaq.jpg"
    },
    {
      full_name: "Bruce Peninsula National Park",
      name: "Bruce Peninsula",
      country: "Canada",
      prov_state: "Ontario",
      lat: 45.226471,   
      long: -81.523045,
      description: "Dramatic cliffs rise from the turquoise waters of Georgian Bay. In large tracts of forest, black bears roam and rare reptiles find refuge in rocky areas and diverse wetlands. Ancient cedar trees spiral from the cliff-edge; a multitude of orchids and ferns take root in a mosaic of habitats. Welcome to the magic of Bruce Peninsula National Park",
      url: "https://www.pc.gc.ca/en/pn-np/on/bruce",
      established: 1987,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/bruce-peninsula.jpg"
    },
    {
      full_name: "Fathom Five National Marine Park ",
      name: "Fathom Five",
      country: "Canada",
      prov_state: "Ontario",
      lat: 45.257159, 
      long: -81.656279,
      description: "Dolomite, 420 million years old, rises through the sparkling waters of Lake Huron to form Fathom Five National Marine Park. This is a freshwater ecosystem of ancient rock formations, cliff-edge forests, fascinating dive sites on 22 shipwrecks, and orchid species both plentiful and rare.",
      url: "https://www.pc.gc.ca/en/amnc-nmca/on/fathomfive",
      established: 1987,
      unesco: false,    
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/fathom-five.jpg"
    },
    {
      full_name: "Saquenay-St. Lawerence Marine Park",
      name: "Saquenay-St. Lawerence",
      country: "Canada",
      prov_state: "Quebec",
      lat: 48.112365, 
      long: -69.663494,
      description: "Watch whales and learn about the fascinating mammals and their habitat. The Saguenay–St. Lawrence Marine Park is recognized as one of the best places in the world for whale watching.",
      url: "https://www.pc.gc.ca/en/amnc-nmca/qc/saguenay",
      established: 1998,
      unesco: false, 
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/saquenay.jpg"
    },
    {
      full_name: "Aulavik National Park",
      name: "Aulavik",
      country: "Canada",
      prov_state: "Northwest Territories",
      lat: 73.748249, 
      long: -119.590888,
      description: "The park encompasses a variety of landscapes from fertile river valleys to polar deserts, buttes and badlands, rolling hills, and bold seacoasts.",
      url: "https://www.pc.gc.ca/en/pn-np/nt/aulavik",
      established: 1992,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/aulavik.jpg"
    },
    {
      full_name: "Gwaii Haanas National Park Reserve and National Marine Conservation Area Reserve",
      name: "Gwaii Haanas",
      country: "Canada",
      prov_state: "British Columbia",
      lat: 52.468274, 
      long: -131.558229,
      description: "Massive moss-draped cedar and Sitka spruce tower above the Haida people’s ancient carved poles and fallen longhouses on the lush rainforest islands of Gwaii Haanas. Skies fill with bald eagles, bears scavenge salmon on wild beaches and the ocean teems with breaching whales, porpoises and sea lions.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/gwaiihaanas",
      established: 1988,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/gwaii-haanas.jpg"
    },
    {
      full_name: "Vuntut National Park",
      name: "Vuntut",
      country: "Canada",
      prov_state: "Yukon",
      lat: 68.384944, 
      long: -139.858033,
      description: "Remote and unspoiled Arctic wilderness, a First Nation’s history dating back millennia and the setting for one of the planet’s great animal migrations await the few who make the trek to Vuntut National Park.",
      url: "https://www.pc.gc.ca/en/pn-np/yt/vuntut",
      established: 1995,
      unesco: false,  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/vuntut.jpg"
    },
    {
      full_name: "Tuktut Nogait National Park",
      name: "Tuktut Nogait",
      country: "Canada",
      prov_state: "Northwest Territories",
      lat: 68.818748, 
      long: -121.748991,
      description: "The landscape and wildlife of the 18,890 sq km national park is seen by those privileged few willing to travel 170 kilometres north of the Arctic Circle.",
      url: "https://www.pc.gc.ca/en/pn-np/nt/tuktutnogait",
      established: 1998,
      unesco: false, 
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/tuktut.jpg"
    },
    {
      full_name: "Wapusk National Park",
      name:"Wapusk ", 
      country: "Canada",
      prov_state: "Manitoba", 
      lat: 57.793851, 
      long: -93.229022,
      description: "Let this expansive wilderness fill you with awe as you visit the remote subarctic that is Wapusk National Park. This 11,475 square kilometre park, at the transition between boreal forest and arctic tundra, protects one of the largest polar bear maternity denning areas in the world. ",
      url: "https://www.pc.gc.ca/en/pn-np/mb/wapusk",
      established: 1996,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/wapusk.jpg"
    },
    {
      full_name: "Sirmilik National Park",
      name: "Sirmilik",
      country: "Canada",
      prov_state: "Nunavut",
      lat: 73.073754,
      long: -79.782056,
      description: "Amid an expansive landscape of glaciers, valleys and red-rock hoodoo spires, nesting seabirds crowd sheer sea cliffs rising from iceberg-dotted waters. Paddle among seals and floating ice, listening for the breaths of narwhal and beluga whales.",
      url: "https://www.pc.gc.ca/en/pn-np/nu/sirmilik",
      established: 2001,
      unesco: false,  
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/sirmilik.jpg"
    },
    {
      full_name: "Gulf Islands National Park Reserve",
      name: "Gulf Islands",
      country: "Canada",
      prov_state: "British Columbia",
      lat: 48.78611, 
      long: -123.16222,
      description: "Eagles and seabirds swirl in the skies above the Salish Sea, sheltered, islet-dotted waters teeming with seals, otters, orcas and pods of porpoises. Kayak, hike or cycle a lush paradise with rare eco-systems basking in a Mediterranean-like climate.",
      url: "https://www.pc.gc.ca/en/pn-np/bc/gulf",
      established: 2003,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/gulf-islands.jpg"
    },
    {
      full_name: "Torngat Mountains National Park",
      name: "Torngat Mountains",
      country: "Canada",
      prov_state: "Newfoundland",
      lat: 59.224605, 
      long: -63.993375,
      description: "A saw-tooth skyline of jagged peaks and glacier-carved fjords plunges towards iceberg-dotted indigo waters as polar bears and caribou roam amid some of Earth’s oldest rocks",
      url: "https://www.pc.gc.ca/en/pn-np/nl/torngats",
      established: 2008,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/torngat.jpg"
    },
    {
      full_name: "Ukkusiksalik National Park",
      name: "Ukkusiksalik",
      country: "Canada",
      prov_state: "Nunavut",
      lat: 65.3441073, 
      long: -87.3125224,
      description: "Polar bears, grizzlies, Arctic wolves and caribou - Ukkusiksalik’s rolling ochre hills and lush tundra thrive with wildlife, and are dotted with archeological reminders of human cultures passing for millennia through this remote wilderness.",
      url: "https://www.pc.gc.ca/en/pn-np/nu/ukkusiksalik",
      established: 2003,
      unesco: false,
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/ukkusiksalik.jpg"
    },
    {
      full_name: "Qausuittuq National Park",
      name: "Qausuittuq",
      country: "Canada",
      prov_state: "Nunavut",
      lat: 76.041786, 
      long: -100.604458,
      description: "Imagine a cluster of islands in a frozen sea, a home for the endangered Peary caribou, a traditional hunting and fishing area that has sustained Inuit of Resolute Bay since the time of their relocation in the 1950’s; Qausuittuq National Park is all of that and more.",
      url: "https://www.pc.gc.ca/en/pn-np/nu/qausuittuq",    
      established: 2015,
      unesco: false,    
      designation: "National Park",
      weather_info: nil,
      photo: "/photos/qausuittuq.jpg"
    }
    ]

parks_american = [
  {
    prov_state: "ME",
    lat: 44.30777545,
    long: -68.30063316,
    description: "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats with high biodiversity, clean air and water, and a rich cultural heritage. Each year, more than 3.3 million people explore seven peaks above 1,000 feet, 158 miles of hiking trails, and 45 miles of carriage roads with 16 stone bridges.",
    designation: "National Park",
    full_name: "Acadia National Park",
    url: "https://www.nps.gov/acad/index.htm",
    weather_info: "Located on Mount Desert Island in Maine, Acadia experiences all four seasons. Summer temperatures range from 45-90F (7-30C). Fall temperatures range from 30-70F (-1-21C). Typically the first frost is in mid-October and first snowfall begins in November and can continue through April with an average accumulation of 73 inches (185 cm). Winter temperatures range from 14-35F (-10 - 2C). Spring temperatures range from 30-70F (-1-21C).",
    name: "Acadia",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/acadia-national-park.jpg"
  },
  {
    prov_state: "UT",
    lat: 38.72261844,
    long: -109.5863666,
    description: "Visit Arches to discover a landscape of contrasting colors, land forms and textures unlike any other in the world. The park has over 2,000 natural stone arches, in addition to hundreds of soaring pinnacles, massive fins and giant balanced rocks. This red-rock wonderland will amaze you with its formations, refresh you with its trails, and inspire you with its sunsets.",
    designation: "National Park",
    full_name: "Arches National Park",
    url: "https://www.nps.gov/arch/index.htm",
    weather_info: "Arches is part of the Colorado Plateau, a \"high desert\" region that experiences wide temperature fluctuations, sometimes over 40 degrees in a single day. The temperate (and most popular) seasons are spring (April-May) and fall (mid-September-October), when daytime highs average 60 to 80 F and lows average 30 to 50 F. Summer temperatures often exceed 100 F, making strenuous exercise difficult. Winters are cold, with highs averaging 30 to 50 F, and lows averaging 0 to 20 F.",
    name: "Arches",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/arches.jpg"
  },
      {
    prov_state: "SD",
    lat: 43.68584846,
    long: -102.482942,
    designation: "National Park",
    description: "The rugged beauty of the Badlands draws visitors from around the world. These striking geologic deposits contain one of the world’s richest fossil beds. Ancient mammals such as the rhino, horse, and saber-toothed cat once roamed here. The park’s 244,000 acres protect an expanse of mixed-grass prairie where bison, bighorn sheep, prairie dogs, and black-footed ferrets live today.",
    full_name: "Badlands National Park",
    url: "https://www.nps.gov/badl/index.htm",
    weather_info: "The Badlands weather is variable and unpredictable with temperature extremes ranging from 116° F to -40° F. Summers are hot and dry with occasional violent thunderstorms. Hailstorms and occasional tornadoes can descend on the Badlands with sudden fury. Winters are typically cold with 12 to 24 inches of total snowfall.",
    name: "Badlands",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/badlands-national-park.jpg"
  },
  {
    prov_state: "TX",
    lat: 29.29817767,
    long: -103.2297897,
    description: "There is a place in Far West Texas where night skies are dark as coal and rivers carve temple-like canyons in ancient limestone. Here, at the end of the road, hundreds of bird species take refuge in a solitary mountain range surrounded by weather-beaten desert. Tenacious cactus bloom in sublime southwestern sun, and diversity of species is the best in the country. This magical place is Big Bend...",
    designation: "National Park",
    full_name: "Big Bend National Park",
    url: "https://www.nps.gov/bibe/index.htm",
    weather_info: "Variable\n-- February through April the park abounds with pleasant and comfortable temperatures.\n-- May through August is hot and can also be stormy. Temperatures regularly reach well over 100 degrees in the lower elevations and along the Rio Grande.\n-- September through January temperatures are cooler; the weather can quickly turn cold at any time during these months.",
    name: "Big Bend",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/big-bend.jpg"
  },
  {
    prov_state: "FL",
    lat: 25.490587,
    long: -80.21023851,
    description: "Within sight of downtown Miami, yet worlds away, Biscayne protects a rare combination of aquamarine waters, emerald islands, and fish-bejeweled coral reefs. Here too is evidence of 10,000 years of human history, from pirates and shipwrecks to pineapple farmers and presidents. Outdoors enthusiasts can boat, snorkel, camp, watch wildlife…or simply relax in a rocking chair gazing out over the bay.",
    designation: "National Park",
    full_name: "Biscayne National Park",
    url: "https://www.nps.gov/bisc/index.htm",
    weather_info: "The park is situated in a subtropical climate, which ensures sunshine year-round. Winters are normally dry and mild, with occasional fronts bringing wind and little rain. Summer brings hot and humid weather with scattered thunderstorms in the afternoons. The average temperature in January is 68 degrees Fahrenheit and 82 in July. The average rainfall for the area is 2.17 inches in January and 3.95 inches in July. June to November is hurricane season.",
    name: "Biscayne",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/biscayne.jpg"
  },
      {
    prov_state: "AK",
    lat: 67.75961636,
    long: -153.2917758,
    description: "This vast landscape does not contain any roads or trails. Visitors discover intact ecosystems where people have lived with the land for thousands of years. Wild rivers meander through glacier-carved valleys, caribou migrate along age-old trails, endless summer light fades into aurora-lit night skies of winter. It remains virtually unchanged except by the forces of nature.",
    designation: "National Park & Preserve",
    full_name: "Gates Of The Arctic National Park & Preserve",
    url: "https://www.nps.gov/gaar/index.htm",
    weather_info: "The climate of Gates of the Arctic National Park & Preserve is generally classified as arctic and sub-arctic, with exceptionally cold winters, relatively mild summers, low annual precipitation, and generally high winds. The weather is influenced by many different systems, and can change rapidly.",
    name: "Gates Of The Arctic",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/gates-of-the-arctic.jpg"
  },
      {
    prov_state: "CA",
    lat: 40.49354575,
    long: -121.4075993,
    description: "Lassen Volcanic National Park is home to steaming fumaroles, meadows freckled with wildflowers, clear mountain lakes, and numerous volcanoes. Jagged peaks tell the story of its eruptive past while hot water continues to shape the land. Lassen Volcanic offers opportunities to discover the wonder and mysteries of volcanoes and hot water for visitors willing to explore the undiscovered.",
    designation: "National Park",
    full_name: "Lassen Volcanic National Park",
    url: "https://www.nps.gov/lavo/index.htm",
    weather_info: "Weather at Lassen can vary dramatically throughout the year.\n\nAverage January temperatures are a high of 40.4 °F (4.7 °C) and a low of 20.8 °F (-6.2 °C). Average July temperatures are a high of 88.4 °F and a low of 49.8 °F. Temperatures reach 90 °F or higher on an average of 36.9 days, and drop to 32 ° or lower on an average of 164 days days annually.",
    name: "Lassen Volcanic",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/lassen-volcanic.jpg"
  },
      {
    prov_state: "CA",
    lat: 37.84883288,
    long: -119.5571873,
    description: "Not just a great valley, but a shrine to human foresight, the strength of granite, the power of glaciers, the persistence of life, and the tranquility of the High Sierra.\n\nFirst protected in 1864, Yosemite National Park is best known for its waterfalls, but within its nearly 1,200 square miles, you can find deep valleys, grand meadows, ancient giant sequoias, a vast wilderness area, and much more.",
    designation: "National Park",
    full_name: "Yosemite National Park",
    url: "https://www.nps.gov/yose/index.htm",
    weather_info: "Yosemite National Park covers nearly 1,200 square miles (3,100 square km) in the Sierra Nevada, with elevations ranging from about 2,000 feet (600 m) to 13,000 ft (4,000 m). Yosemite receives 95% of its precipitation between October and May (and over 75% between November and March). Most of Yosemite is blanketed in snow from about November through May. (Yosemite Valley can be rainy or snowy in any given winter storm.)",
    name: "Yosemite",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/yosemite.jpg"
  },
      {
    prov_state: "UT",
    lat: 37.58399144,
    long: -112.1826689,
    description: "Hoodoos (irregular columns of rock) exist on every continent, but here is the largest concentration found anywhere on Earth. Situated along a high plateau at the top of the Grand Staircase, the park's high elevations include numerous life communities, fantastic dark skies, and geological wonders that defy description.",
    designation: "National Park",
    full_name: "Bryce Canyon National Park",
    url: "https://www.nps.gov/brca/index.htm",
    weather_info: "http://forecast.weather.gov/MapClick.php?lat=37.63&lon=-112.17#.VpUamdHUhaR",
    name: "Bryce Canyon",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/bryce-canyon.jpg"
  },
      {
    prov_state: "UT",
    lat: 38.24555783,
    long: -109.8801624,
    description: "Canyonlands invites you to explore a wilderness of countless canyons and fantastically formed buttes carved by the Colorado River and its tributaries. Rivers divide the park into four districts: Island in the Sky, The Needles, The Maze, and the rivers themselves. These areas share a primitive desert atmosphere, but each offers different opportunities for sightseeing and adventure.",
    designation: "National Park",
    full_name: "Canyonlands National Park",
    url: "https://www.nps.gov/cany/index.htm",
    weather_info: "Canyonlands is part of the Colorado Plateau, a \"high desert\" region that experiences wide temperature fluctuations, sometimes over 40 degrees in a single day. The temperate (and most popular) seasons are spring (April-May) and fall (mid-September-October), when daytime highs average 60 to 80 F and lows average 30 to 50 F. Summer temperatures often exceed 100 F, making strenuous exercise difficult. Winters are cold, with highs averaging 30 to 50 F, and lows averaging 0 to 20 F.",
    name: "Canyonlands",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/canyonlands.jpg"
  },
      {
    prov_state: "UT",
    lat: 37.29839254,
    long: -113.0265138,
    description: "Follow the paths where ancient native people and pioneers walked. Gaze up at massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky. Experience wilderness in a narrow slot canyon. Zion’s unique array of plants and animals will enchant you as you absorb the rich history of the past and enjoy the excitement of present day adventures.",
    designation: "National Park",
    full_name: "Zion National Park",
    url: "https://www.nps.gov/zion/index.htm",
    weather_info: "Zion is known for a wide range of weather conditions. Temperatures vary with changes in elevation and day/night temperatures may differ by over 30°F.\n\nIn summer, temperatures in Zion National Park often exceed 100°F/38°C. Zion experiences monsoons from mid-July into September that results in an increased risk of flash floods. Always be aware of the threat of storms and lightning and be prepared for a wide range of weather conditions. Winters are generally mild.",
    name: "Zion",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/zion.jpg"
  },
  {
    prov_state: "CO",
    lat: 38.57779869,
    long: -107.7242756,
    description: "Big enough to be overwhelming, still intimate enough to feel the pulse of time, Black Canyon of the Gunnison exposes you to some of the steepest cliffs, oldest rock, and craggiest spires in North America. With two million years to work, the Gunnison River, along with the forces of weathering, has sculpted this vertical wilderness of rock, water, and sky.",
    designation: "National Park",
    full_name: "Black Canyon Of The Gunnison National Park",
    url: "https://www.nps.gov/blca/index.htm",
    weather_info: "Today's Weather: http://www.weather.com/weather/today/l/NPBLCA:13:US\n\nCLIMATE\nWeather can vary greatly throughout the day. Summer daytime temperatures range between 55 to 90F (13 to 32C), nights 45 to 60F (7 to 16C). Winter daytime temperatures range between 15 to 40F (-9 to 4C), nights 10 to 20F (-12 to -6C).\n\nAfternoon thunderstorms are common during the summer. Snow accumulation varies greatly year to year. Layered clothing appropriate for the season is recommended.",
    name: "Black Canyon Of The Gunnison",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/black_canyon_and_gunnison.jpg"
  },
  {
    prov_state: "CO",
    lat: 37.23908345,
    long: -108.4624032,
    description: "Mesa Verde National Park was established in 1906 to preserve and interpret the archeological heritage of the Ancestral Pueblo people who made it their home for over 700 years, from 600 to 1300 CE. Today, the park protects nearly 5,000 known archeological sites, including 600 cliff dwellings. These sites are some of the most notable and best preserved in the United States.",
    designation: "National Park",
    full_name: "Mesa Verde National Park",
    url: "https://www.nps.gov/meve/index.htm",
    weather_info: "Spring: Temps range from 40 F to 70 F, but snowstorms can occur as late as May. \n\nSummer: Temps can reach well into the 90s F. Thunderstorms are common in July and August. Be prepared to bring and DRINK plenty of water.\n\nFall: Temps can range from 50 F to 75 F. Snowstorms can occur as early as October. \n\nWinter: Temps can range from the teens to low 30s F. Icy roads are common. Snow tires, all-wheel drive, or chains, may be required. Be prepared with water, snacks, and layers of warm clothing.",
    name: "Mesa Verde",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/mesa-verde.jpg"
  },
  {
    prov_state: "CO",
    lat: 40.3556924,
    long: -105.6972879,
    description: "Rocky Mountain National Park’s 415 square miles encompass and protect spectacular mountain environments. Enjoy Trail Ridge Road – which crests at over 12,000 feet including many overlooks to experience the subalpine and alpine worlds – along with over 300 miles of hiking trails, wildflowers, wildlife, starry nights, and fun times. In a world of superlatives, Rocky is on top!",
    designation: "National Park",
    full_name: "Rocky Mountain National Park",
    url: "https://www.nps.gov/romo/index.htm",
    weather_info: "Winter (Dec–Mar): cold weather, deep snow at higher elevations, and seasonal closures of facilities and roads. Spring (April–May): unpredictable weather, with a mix of warm sunny days and cool days with heavy snow and rain. Many trails are still snow-covered. Trail Ridge Road opens in late May. Summer (Jun–Aug): warmer weather, thunderstorms, and wildflowers. Most park roads and facilities are open. Fall (Sep–Nov): crisp air, blue skies, fall colors, and the elk rut. Trail Ridge Road closes mid-October.",
    name: "Rocky Mountain",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/rocky-mountain-national-park.jpg"
  },
  {
    prov_state: "AZ",
    lat: 36.17280161,
    long: -112.6836024,
    description: "Unique combinations of geologic color and erosional forms decorate a canyon that is 277 river miles (446km) long, up to 18 miles (29km) wide, and a mile (1.6km) deep. Grand Canyon overwhelms our senses through its immense size.\n\nSouth Rim is open all year.  North Rim is closed for the winter.  \n\nOn February 26, 1919, Grand Canyon became a National Park. This is our Centennial Year!",
    designation: "National Park",
    full_name: "Grand Canyon National Park",
    url: "https://www.nps.gov/grca/index.htm",
    weather_info: "This weather varies with cold winters and mild pleasant summers, moderate humidity, and considerable diurnal temperature changes at the higher elevations, with hot and drier summers at the bottom of the Grand Canyon along with cool damp winters. Summer thunderstorms and winter snowfall adds to the weather variety in this region.",
    name: "Grand Canyon",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/grand-canyon.jpg"
  },
      {
    prov_state: "AZ",
    lat: 34.98387664,
    long: -109.7877678,
    description: "Did you know that Petrified Forest is more spectacular than ever? While the park has all the wonders known for a century, there are many new adventures and discoveries to share. There are backcountry hikes into areas never open before such as Red Basin and little known areas like the Martha's Butte. There are new exhibits that bring the stories to life. Come rediscover Petrified Forest!",
    designation: "National Park",
    full_name: "Petrified Forest National Park",
    url: "https://www.nps.gov/pefo/index.htm",
    weather_info: "Petrified Forest National Park is a semi-arid grassland. Temperatures range from above 100° F (38° C) to well below freezing. About 10 inches (25.4 cm) of moisture comes during infrequent snow in the winter and often dramatic summer thunder-storms. Animals and plants are adapted to extremes in temperature and moisture. You should be ready too. Check out the forecast before you arrive and plan accordingly.",
    name: "Petrified Forest",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/petrified-forest.jpg"
  },
      {
    prov_state: "AZ",
    lat: 32.20909636,
    long: -110.7574974,
    description: "Tucson, Arizona is home to the nation's largest cacti. The giant saguaro is the universal symbol of the American west. These majestic plants, found only in a small portion of the United States, are protected by Saguaro National Park, to the east and west of the modern city of Tucson. Here you have a chance to see these enormous cacti, silhouetted by the beauty of a magnificent desert sunset.",
    designation: "National Park",
    full_name: "Saguaro National Park",
    url: "https://www.nps.gov/sagu/index.htm",
    weather_info: "Winter Season\nWith daytime temperature from the low 50's to the high 70's\n\nSummer Season \nAs we get deeper into the summer season, temperatures will range from mid-80's to low 100's. This is a great time to experience the desert as the day breaks or in the late of the day as the sun disappears behind the surrounding mountain ranges. During the late spring and summer months Saguaro National Park only offers interpretive programs on an intermittent basis.",
    name: "Saguaro",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/saguaro.jpg"
  },
      {
    prov_state: "FL",
    lat: 24.64884965,
    long: -82.87176297,
    description: "Almost 70 miles (113 km) west of Key West lies the remote Dry Tortugas National Park. This 100-square mile park is mostly open water with seven small islands.  Accessible only by boat or seaplane, the park is known the world over as the home of magnificent Fort Jefferson, picturesque blue waters, superlative coral reefs and marine life, and the vast assortment of bird life that frequents the area.",
    designation: "National Park",
    full_name: "Dry Tortugas National Park",
    url: "https://www.nps.gov/drto/index.htm",
    weather_info: "The climate in the Dry Tortugas is subtropical, which basically means that it has warm and tropical weather in the range of 60°F to 90°F. The two main seasons are the winter stormy season from December through March which is windier and sees rougher seas, and the summertime tropical storm season from June through November where there is a higher chance of isolated storms. During the summers it is hot and humid. During the winter the temperature is milder and drier.",
    name: "Dry Tortugas",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/dry_tortugas.jpg"
  },
      {
    prov_state: "FL",
    lat: 25.37294225,
    long: -80.88200301,
    description: "Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee,  American crocodile, and the elusive Florida panther.\n\nAn international treasure as well -  a World Heritage Site, International Biosphere Reserve, a Wetland of International Importance, and a specially protected area under the Cartagena Treaty.",
    designation: "National Park",
    full_name: "Everglades National Park",
    url: "https://www.nps.gov/ever/index.htm",
    weather_info: "The climate in Florida is known to be mild and sunny.The average annual temperatures for South Florida and the Keys range from 74° to 77°F (23° to 25°C). There are two seasons at the Everglades National Park: the wet season and the dry season. The wet season runs from Mid-May to November and the dry season runs from December to mid-May.",
    name: "Everglades",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/everglades.jpg"
  },
      {
    prov_state: "WA",
    lat: 46.86075416,
    long: -121.7043885,
    description: "Ascending to 14,410 feet above sea level, Mount Rainier stands as an icon in the Washington landscape. An active volcano, Mount Rainier is the most glaciated peak in the contiguous U.S.A., spawning five major rivers. Subalpine wildflower meadows ring the icy volcano while ancient forest cloaks Mount Rainier’s lower slopes. Wildlife abounds in the park’s ecosystems. A lifetime of discovery awaits.",
    designation: "National Park",
    full_name: "Mount Rainier National Park",
    url: "https://www.nps.gov/mora/index.htm",
    weather_info: "Weather patterns at Mount Rainier are strongly influenced by the Pacific Ocean and elevation. The climate is generally cool and rainy, with summer highs in the 60s and 70s. While July and August are the sunniest months of the year, rain is very likely in spring, fall, and winter. Visitors should be aware that mountain weather is very changeable. In the higher elevations, like Paradise, winter can last from November to May with many feet of snow on the ground.",
    name: "Mount Rainier",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/mount-rainier.jpg"
  },
      {
    prov_state: "WA",
    lat: 48.71171756,
    long: -121.2069423,
    description: "Less than three hours from Seattle, an alpine landscape beckons. Discover communities of life adapted to moisture in the west and recurring fire in the east. Explore jagged peaks crowned by more than 300 glaciers. Listen to cascading waters in forested valleys. Witness a landscape sensitive to the Earth's changing climate. Help steward the ecological heart of the Cascades.",
    designation: "National Park",
    full_name: "North Cascades National Park",
    url: "https://www.nps.gov/noca/index.htm",
    weather_info: "The best weather for visiting the North Cascades generally occurs between mid-June and late-September. Summer daytime temperatures average in the 70's F. Snow is off most trails by mid-July. Autumn and Spring are popular for color and wildlife. Storms are common: always be prepared for a few days of rain and wind. The east side of the Cascade Mountains (Lake Chelan National Recreation Area) is drier and warmer in the summer than the west side. Summer temperatures at Stehekin reach the 90's F.",
    name: "North Cascades",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/north-cascades.jpg"
  },
  {
    prov_state: "WA",
    lat: 47.80392754,
    long: -123.6663848,
    description: "With its incredible range of precipitation and elevation, diversity is the hallmark of Olympic National Park. Encompassing nearly a million acres, the park protects a vast wilderness, thousands of years of human history, and several distinctly different ecosystems, including glacier-capped mountains, old-growth temperate rain forests, and over 70 miles of wild coastline. Come explore!",
    designation: "National Park",
    full_name: "Olympic National Park",
    url: "https://www.nps.gov/olym/index.htm",
    weather_info: "Summers tend to be fair and warm, with high temperatures between 65 and 75 degrees F. July, August and September are the driest months, with heavier precipitation during the rest of the year. While winters are mild at lower elevation, snowfall can be heavy in the mountains. It is common for different weather conditions to exist within the park at the same time.  At any time of year, visitors should come prepared for a variety of conditions.",
    name: "Olympic",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/olympic.jpg"
  },
  {
    prov_state: "HI",
    lat: 20.70693015,
    long: -156.1591775,
    description: "This special place vibrates with stories of ancient and modern Hawaiian culture and protects the bond between the land and its people. The park also cares for endangered species, some of which exist nowhere else. Come visit this special place - renew your spirit amid stark volcanic landscapes and sub-tropical rain forest with an unforgettable hike through the backcountry.",
    designation: "National Park",
    full_name: "Haleakal&#257; National Park",
    url: "https://www.nps.gov/hale/index.htm",
    weather_info: "On any given day, the temperatures in the park can range from a high of 80°F (27°C) in Kīpahulu to a low of 30°F (-1°C) at the summit. In either area clouds and rain can quickly replace warm sunshine.\nWeather in the high-elevation summit and wilderness areas of the park is highly unpredictable and changes often. Cool temperatures, intense solar radiation, and rapidly moving clouds are characteristic. On average, the temperature drops about 3°F for every 1,000 foot rise in elevation.",
    name: "Haleakal&#257;",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/haleakala.jpg"
  },
  {
    prov_state: "HI",
    lat: 19.3355036,
    long: -155.4700257,
    description: "Hawai‘i Volcanoes National Park protects some of the most unique geologic, biologic, and cultural landscapes in the world. Extending from sea level to the summit of Mauna Loa at 13,677 feet, the park encompasses the summits of two of the world's most active volcanoes - Kīlauea and Mauna Loa. Learn more about this special place and traditional Hawaiian culture connected to these landscapes.",
    designation: "National Park",
    full_name: "Hawai'i Volcanoes National Park",
    url: "https://www.nps.gov/havo/index.htm",
    weather_info: "The weather at Kīlauea's summit (4000' elevation) varies daily and may be rainy and chilly any time of the year. Temperature varies by elevation. At the summit of the volcano, temperatures may be 12 to 15 degrees cooler than at sea level. The coastal plain at the end of Chain of Craters Road, where lava crossed the road in 2003, is often hot, dry, and windy with the possibility of passing showers.",
    name: "Hawai'i Volcanoes",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/hawaii-volcano.jpg"
  },
  {
    prov_state: "SD",
    lat: 43.58012365,
    long: -103.4394709,
    description: "Bison, elk, and other wildlife roam the rolling prairie grasslands and forested hillsides of one of America's oldest national parks. Below the remnant island of intact prairie sits Wind Cave, one of the longest and most complex caves in the world. Named for barometric winds at its entrance, this maze of passages is home to boxwork, a unique formation rarely found elsewhere.",
    designation: "National Park",
    full_name: "Wind Cave National Park",
    url: "https://www.nps.gov/wica/index.htm",
    weather_info: "Spring:  Highs range from 50 - 70 F with highly variable weather. Spring is the park's wettest season.\n\nSummer:  Warm and generally dry with highs in the 80s F. Thunderstorms are common and can produce large hail and severe lightning. \n\nFall:  Generally dry with warm days and cool nights. Highs in the 50s - 60s F. Lows below freezing are common.\n\nWinter: Highs in the upper 30s F with lows in the 10s F. Snowfall averages 30 inches annually, periodically closing park roads.",
    name: "Wind Cave",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/wind-cave.jpg"
  },
  {
    prov_state: "TX",
    lat: 31.92304462,
    long: -104.885527,
    description: "Guadalupe Mountains National Park protects the world's most extensive Permian fossil reef, the four highest peaks in Texas, an environmentally diverse collection of flora and fauna, and the stories of lives shaped through conflict, cooperation and survival. Come experience mountains and canyons, desert and dunes, night skies and spectacular vistas within a place unlike any other within the NPS.",
    designation: "National Park",
    full_name: "Guadalupe Mountains National Park",
    url: "https://www.nps.gov/gumo/index.htm",
    weather_info: "Weather in the Guadalupe Mountains can change in an instant. In the Spring and Summer, average temperatures vary with highs between 70F-80F+ with evening lows in the 40F-60F range. The Fall and Winter bring milder temperatures with highs in between 50F-60F with evening lows in the 30F-50F range.",
    name: "Guadalupe Mountains",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/guadalupe.jpg"
  },
  {
    prov_state: "WY",
    lat: 43.81853565,
    long: -110.7054666,
    description: "Rising above a scene rich with extraordinary wildlife, pristine lakes, and alpine terrain, the Teton Range stands monument to the people who fought to protect it. These are mountains of the imagination. Mountains that led to the creation of Grand Teton National Park where you can explore over two hundred miles of trails, float the Snake River or enjoy the serenity of this remarkable place.",
    designation: "National Park",
    full_name: "Grand Teton National Park",
    url: "https://www.nps.gov/grte/index.htm",
    weather_info: "Jackson Hole has long, cold winters; snow and frost are possible any month. \nmid-April, May & June - Mild days and cool nights alternate with rain and snow.\nJuly & August - Warm days and cool nights prevail, with afternoon thundershowers common.\nSeptember, October & November - Sunny days and cold nights alternate with rain and occasional snowstorms.\nDecember to mid-April - Between storms the days are sunny and nights are frigid. Snow blankets the mountains and valley.",
    name: "Grand Teton",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/grand-teton.jpg"
  },
  {
    prov_state: "ID,MT,WY",
    lat: 44.59824417,
    long: -110.5471695,
    description: "On March 1, 1872, Yellowstone became the first national park for all to enjoy the unique hydrothermal wonders. Preserved within are Earth's most active and diverse geysers, hot springs, mudpots, and fumaroles.",
    designation: "National Park",
    full_name: "Yellowstone National Park",
    url: "https://www.nps.gov/yell/index.htm",
    weather_info: "Yellowstone's weather can vary quite a bit, even in a single day. In the summer, daytime highs can exceed 70F (25C), only to drop 20 or more degrees when a thunderstorm rolls through. It can snow during any month of the year, and winter lows frequently drop below zero, especially at night. Bring a range of clothing options, including a warm jacket and rain gear, even in the summer.",
    name: "Yellowstone",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/yellowstone.jpg"
  },
  {
    prov_state: "AR",
    lat: 34.52414366,
    long: -93.06332936,
    description: "Water. That's what first attracted people, and they have been coming here ever since to use these soothing thermal waters to heal and relax. Rich and poor alike came for the baths, and a thriving city built up around the hot springs. Together nicknamed \"The American Spa,\" Hot Springs National Park today surrounds the north end of the city of Hot Springs, Arkansas. Come discover it for yourself.",
    designation: "National Park",
    full_name: "Hot Springs National Park",
    url: "https://www.nps.gov/hosp/index.htm",
    weather_info: "Temperatures range from >100°F (38°C) to <20°F (-7°C). \nSpring has the highest average rainfall. \nSummer temperatures frequently reach the triple-digit range and high humidity \nFall begins fall colors and cooler temperatures. Frost starts to become more common.\nWinter  temperatures often fall below 33 degrees and occasionally drop below 0. Roads may be icy. \nYour visit can be more enjoyable by checking the forecast and coming prepared for hikes or walks in the park.",
    name: "Hot Springs",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/hot-springs.jpg"
  },
  {
    prov_state: "KY",
    lat: 37.19760458,
    long: -86.13090198,
    description: "Mammoth Cave National Park preserves the cave system and a part of the Green River valley and hilly country of south central Kentucky. This is the world's longest known cave system, with more than 400 miles (643 km) explored. Early guide Stephen Bishop called the cave a \"grand, gloomy and peculiar place,\" but its vast chambers and complex labyrinths have earned its name - Mammoth.",
    designation: "National Park",
    full_name: "Mammoth Cave National Park",
    url: "https://www.nps.gov/maca/index.htm",
    weather_info: "Kentucky has a moderate climate with warm, yet moist conditions. Summers average in the high 80s; winters average in the low 40s. Southern Kentucky, where Mammoth Cave is located, receives the highest average precipitation for the state, about 50 inches per year, mostly in spring. Winter can bring mild to moderate snow and ice. Storms happen year-round, and can include tornadoes and flooding in low-lying areas, but severe weather is infrequent. The temperature deep in the cave is a constant 54°F (12°C).",
    name: "Mammoth Cave",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/mammoth-cave.jpg"
  },
  {
    prov_state: "MI",
    lat: 48.01145819,
    long: -88.82780657,
    description: "Explore a rugged, isolated island, far from the sights and sounds of civilization. Surrounded by Lake Superior, Isle Royale offers unparalleled solitude and adventures for backpackers, hikers, boaters, kayakers, canoeists and scuba divers. Here, amid stunning scenic beauty, you'll find opportunities for reflection and discovery, and make memories that last a lifetime.",
    designation: "National Park",
    full_name: "Isle Royale National Park",
    url: "https://www.nps.gov/isro/index.htm",
    weather_info: "Isle Royale National Park is a remote island wilderness in the middle of Lake Superior.  Weather influences traveling to and from the island, as well as your trip once you arrive.  For the most up-to-date weather information, call (906) 482-0984 or email isro_parkinfo@nps.gov prior to your trip.",
    name: "Isle Royale",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/isle-royale.jpg"
  },
      {
    prov_state: "MN",
    lat: 48.48370609,
    long: -92.8382913,
    description: "With over 40% of the park water, Voyageurs is a maze of interconnected water highways. Plan ahead before coming to this water park by bringing your own watercraft, reserving a watercraft, or taking a park ranger boat tour.",
    designation: "National Park",
    full_name: "Voyageurs National Park",
    url: "https://www.nps.gov/voya/index.htm",
    weather_info: "There are four distinct seasons in Voyageur country.  The air is temperate during June, July, and August when periods of fine, mild weather prevail.  The frost-free season averages 120 days from June to mid-September.  The average ice-out date is May 3 but varies year to year.  Annual precipitation (rain and snow) averages 25-28 inches in the park and snowfall ranges from 55-70 inches, but is highly variable.  The first measurable snowfall occurs in late October and the last in late April or early May.",
    name: "Voyageurs",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/voyageurs-national.jpg"
  },
  {
    prov_state: "MT",
    lat: 48.68414678,
    long: -113.8009306,
    description: "Come and experience Glacier's pristine forests, alpine meadows, rugged mountains, and spectacular lakes. With over 700 miles of trails, Glacier is a hiker's paradise for adventurous visitors seeking wilderness and solitude. Relive the days of old through historic chalets, lodges, and the famous Going-to-the-Sun Road. Explore Glacier National Park and discover what awaits you.",
    designation: "National Park",
    full_name: "Glacier National Park",
    url: "https://www.nps.gov/glac/index.htm",
    weather_info: "Glacier's weather is highly variable and can be extreme. Expect warm sunny summer days and in the winter the temperatures can fall well below freezing. Glacier's geography, straddling the Continental Divide, sets the stage for clashes of two very different climates. Warm, wet Pacific air moves in from the west, and cold dry Arctic air from the northeast. They meet at the Divide.",
    name: "Glacier",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/glacier.jpg"
  },
  {
    prov_state: "CA,NV",
    lat: 36.48753731,
    long: -117.134395,
    description: "In this below-sea-level basin, steady drought and record summer heat make Death Valley a land of extremes. Yet, each extreme has a striking contrast. Towering peaks are frosted with winter snow. Rare rainstorms bring vast fields of wildflowers. Lush oases harbor tiny fish and refuge for wildlife and humans. Despite its morbid name, a great diversity of life survives in Death Valley.",
    designation: "National Park",
    full_name: "Death Valley National Park",
    url: "https://www.nps.gov/deva/index.htm",
    weather_info: "AUTUMN arrives in late October, with warm but pleasant temperatures and generally clear skies.\nWINTER has cool days, chilly nights and rarely, rainstorms. With snow capping the high peaks and low angled winter light, this season is especially beautiful for exploring the valley.\nSPRINGTIME is the most popular time to visit Death Valley. Besides warm and sunny days, the possibility of spring wildflowers is a big attraction.\nSUMMER starts early in Death Valley. By May the valley is too hot for most visitors",
    name: "Death Valley",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/death-valley.jpg"
  },
  {
    prov_state: "NM",
    lat: 32.14089463,
    long: -104.5529688,
    description: "High ancient sea ledges, deep rocky canyons, flowering cactus, and desert wildlife—treasures above the ground in the Chihuahuan Desert. Hidden beneath the surface are more than 119 caves—formed when sulfuric acid dissolved limestone leaving behind caverns of all sizes.",
    designation: "National Park",
    full_name: "Carlsbad Caverns National Park",
    url: "https://www.nps.gov/cave/index.htm",
    weather_info: "Carlsbad Caverns National Park is located in the Chihuahuan Desert in southeast New Mexico. Summers are hot with temperatures between 90°F (32°C) and low 100s °F (38°C). Windy conditions and mild temperatures are common in early spring (March-May) with frequent rain in early fall (August-September). This part of the country also sees cold temperatures in the winter with occasional snow and icy conditions. Most days, the park is enveloped by a gorgeous blue sky with very few clouds, 278 sunny days a year!",
    name: "Carlsbad Caverns",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/carlsbad.jpg"
  },
  {
    prov_state: "NC,TN",
    lat: 35.60116374,
    long: -83.50818326,
    description: "Ridge upon ridge of forest straddles the border between North Carolina and Tennessee in Great Smoky Mountains National Park. World renowned for its diversity of plant and animal life, the beauty of its ancient mountains, and the quality of its remnants of Southern Appalachian mountain culture, this is America's most visited national park.",
    designation: "National Park",
    full_name: "Great Smoky Mountains National Park",
    url: "https://www.nps.gov/grsm/index.htm",
    weather_info: "Elevations in the park range from approximately 875 feet to 6,643 feet and the topography can drastically affect local weather. Temperatures can vary 10-20 degrees Fahrenheit from mountain base to top, and clear skies lower down do not guarantee equally pleasant weather at higher elevations. Visit http://www.nps.gov/grsm/planyourvisit/weather.htm for seasonal weather information and links to local forecasts.",
    name: "Great Smoky Mountains",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/smoky.jpg"
  },
  {
    prov_state: "ND",
    lat: 47.17777274,
    long: -103.4300083,
    description: "When Theodore Roosevelt came to Dakota Territory to hunt bison in 1883, he was a skinny, young, spectacled dude from New York. He could not have imagined how his adventure in this remote and unfamiliar place would forever alter the course of the nation. The rugged landscape and strenuous life that TR experienced here would help shape a conservation policy that we still benefit from today.",
    designation: "National Park",  
    full_name: "Theodore Roosevelt National Park",
    url: "https://www.nps.gov/thro/index.htm",
    weather_info: "In winter, some or all park roads may be closed due to snow.",
    name: "Theodore Roosevelt",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/theodore.jpg"
  },
  {
    prov_state: "OH",
    lat: "41.26093905",
    long: "-81.57116722",
    description: "Though a short distance from the urban areas of Cleveland and Akron, Cuyahoga Valley National Park seems worlds away. The park is a refuge for native plants and wildlife, and provides routes of discovery for visitors. The winding Cuyahoga River gives way to deep forests, rolling hills, and open farmlands. Walk or ride the Towpath Trail to follow the historic route of the Ohio & Erie Canal.",
    designation: "National Park",
    full_name: "Cuyahoga Valley National Park",
    url: "https://www.nps.gov/cuva/index.htm",
    weather_info: "Spring's rain and warming temperatures bring new leaves on trees, blooming wildflowers, and visitors anxious get out on the trail. \n\nSummer temperatures range from 49 to 95 degrees F and can be humid. Dressing in layers is advisable. \n\nFall temperatures can range from low 70s during the day to freezing during the night. Fall foliage often peaks in mid-October.\n\nWinter weather conditions can rapidly change, due to the lake effect snow from Lake Erie. Temperatures vary from mid-30s to below zero.",
    name: "Cuyahoga Valley",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/cuyahoga.jpg"
  },
  {
    prov_state: "OR",
    lat: "42.94065854",
     long: "-122.1338414",
    description: "Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak. Scientists marvel at its purity: fed by rain and snow, it’s the deepest lake in the USA and one of the most pristine on earth. Artists, photographers, and sightseers gaze in wonder at its blue water and stunning setting atop the Cascade Mountain Range.",
    designation: "National Park",
    full_name: "Crater Lake National Park",
    url: "https://www.nps.gov/crla/index.htm",
    weather_info: "October through June Crater Lake is snow covered. Snowfall averages 533 inches (1,350 cm) annually, and by early spring, it is typical to have ten to fifteen feet (4 meters) of snow on the ground. \n\nJuly, August, and September are drier and warmer. A typical daytime high temperature during these three months is around 67°F (19°C), but can range from 40°F to 80°F or more (4°C to 27°C). Temperatures cool off rapidly in the evening, with a typical nighttime low around 40°F (4°C).",
    name: "Crater Lake",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/crater-lake.jpg"
  },
  
  {
    prov_state: "SC",
    lat: "33.79187523", 
    long: "-80.74867805",
    description: "Astonishing biodiversity exists in Congaree National Park, the largest intact expanse of old growth bottomland hardwood forest remaining in the southeastern United States. Waters from the Congaree and Wateree Rivers sweep through the floodplain, carrying nutrients and sediments that nourish and rejuvenate this ecosystem and support the growth of national and state champion trees.",
    designation: "National Park",
    full_name: "Congaree National Park",
    url: "https://www.nps.gov/cong/index.htm",
    weather_info: "Check the forecast before getting on the road. Conditions can change rapidly within the park. Flooding can happen with little or no warning, so make sure to check water levels for Cedar Creek and the Congaree River.",
    name: "Congaree",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/congaree.jpg"
  },
  
  {
    prov_state: "VA",
    lat: "38.49236644", 
    long: "-78.46907715",
    description: "Just 75 miles from the bustle of Washington, D.C., Shenandoah National Park is your escape to recreation and re-creation. Cascading waterfalls, spectacular vistas, quiet wooded hollows—take a hike, meander along Skyline Drive, or picnic with the family. 200,000 acres of protected lands are haven to deer, songbirds, the night sky…and you. Plan a Shenandoah escape today!",
    designation: "National Park",
    full_name: "Shenandoah National Park",
    url: "https://www.nps.gov/shen/index.htm",
    weather_info: "Shenandoah experiences four distinct seasons. Best known for its fall foliage, the park is also spectacular in spring when the wildflowers and trees are in full bloom. Summer brings lush greens and relief from the hot valleys. The park's elevation encourages as much as a 10 degree temperature difference. In winter, this means that when surrounding lowlands are experiencing rain, the the park can be blanketed in snow and ice. It's always a good idea to be prepared for varying weather.",
    name: "Shenandoah",
    img: open_asset("usa_np.jpg"),
    photo: "/photos/American Parks/shenandoah.jpg"
  }
      ]
  

parks_american.select do |park|
  Park.create(park)
  
end


parks_canadian.select do |park|
    Park.create(park)
end


